[environment]
root = [".", "py-src"]
python-version = "3.11"

[src]
include = [
    "py-src/**/*.py",
    "py-src/**/*.pyi",
    # Uncomment after python-version = "3.15"
    # "tests/*.py",
]
exclude = [
    "tests/test_wasm.py",
]
