// This file auto-generated by scripts/generate_tables.py; DO NOT EDIT MANUALLY!!!

#[rustfmt::skip]
mod standard;
#[rustfmt::skip]
mod urlsafe;

pub use standard::STANDARD_PAIRS;
pub use urlsafe::URLSAFE_PAIRS;
