from pathlib import Path


OUT = Path(__file__).resolve().parents[1] / "src" / "encode" / "tables"

ALPHABETS = {
    "standard": b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    "urlsafe": b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
}

MOD_RS = """\
// This file auto-generated by scripts/generate_tables.py; DO NOT EDIT MANUALLY!!!

#[rustfmt::skip]
mod standard;
#[rustfmt::skip]
mod urlsafe;

pub use standard::STANDARD_PAIRS;
pub use urlsafe::URLSAFE_PAIRS;
"""

TABLE_RS = """\
// This file auto-generated by scripts/generate_tables.py; DO NOT EDIT MANUALLY!!!

pub const {name}: [u16; 4096] = [
{rows}
];
"""


def render(name: str, alphabet: bytes) -> str:
    values = [alphabet[i >> 6] | alphabet[i & 63] << 8 for i in range(4096)]
    rows = "\n".join(
        "    " + ", ".join(f"0x{x:04x}" for x in values[i : i + 8]) + ","
        for i in range(0, 4096, 8)
    )
    return TABLE_RS.format(name=name, rows=rows)


for module, alphabet in ALPHABETS.items():
    (OUT / f"{module}.rs").write_text(
        render(f"{module.upper()}_PAIRS", alphabet),
        encoding="utf-8",
    )

(OUT / "mod.rs").write_text(MOD_RS, encoding="utf-8")